name: Node.js CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: node:20
    steps:
    - uses: actions/checkout@v4
      with:
        node-version: 20.x

    - name: run backend
      working-directory: backend
      run: npm ci
      run: cd admin-service
      run: node server.js

    - name: run client
      working-directory: backend/client-service
      run: node server.js

    - name: run llm
      working-directory: backend/llm-service
      run: node server.js

    - name: run auth
      working-directory: backend/user-authentication-service
      run: node server.js
    
    - name: run frontend
      working-directory: frontend
      run: |
        npm ci
        npm start
